JDCP-15: Reschedule open stream request on timeout
couchbaselabs/java-dcp-client pull request #16
Opened 2016-09-30 10:29 UTC by avsej

2016-09-30 10:39 UTC, daschl requested changes

2016-09-30 10:39 UTC, daschl commented on src/main/java/com/couchbase/client/dcp/conductor/DcpChannel.java
> +                        LOGGER.debug("Timeout on open Stream against {} with vbid: {}", channel.remoteAddress(), vbid);
should this be warn?

2016-09-30 10:39 UTC, daschl commented on src/main/java/com/couchbase/client/dcp/conductor/OperationTimeoutException.java
> +public class OperationTimeoutException extends CouchbaseException {
ChannelTimeoutException so that it indicates it has something to do with the channel? Operation is very generic

2016-09-30 10:39 UTC, daschl commented on src/main/java/com/couchbase/client/dcp/config/ClientEnvironment.java
> +        public Builder setOpenStreamTimeout(long openStreamTimeout) {
maybe startStream timeout since thats how the method is called on the client api?

2016-09-30 10:39 UTC, daschl commented on src/main/java/com/couchbase/client/dcp/conductor/Conductor.java
> +            .retryWhen(anyOf(NotConnectedException.class, OperationTimeoutException.class)
👍

2016-09-30 10:53 UTC, daschl approved these changes

2016-10-04 08:23 UTC, daschl commented
@avsej how are we on this?

2016-10-06 08:48 UTC, avsej commented
@daschl I would hold this off, as it is not clear why we didn't receive it and it is not safe to retry this message when server thinks that stream has been created already

2016-10-12 07:39 UTC, closed without merging